services:
  csi-logger:
    build: .
    container_name: csi-logger
    devices:
      - /dev:/dev
    privileged: true
    volumes:
      - ./logs:/app/logs
      - /opt/ros2-csi-msgs:/opt/ros2-csi-msgs:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # - ROS_DOMAIN_ID=0
      # - ROS_LOCALHOST_ONLY=0
    network_mode: "host"
    ipc: host